# Generated by Django 2.2.5 on 2019-11-11 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Year one', '100'), ('Year two', '200'), ('Year three', '300'), ('Year four', '400'), ('Year five', '500'), ('POST GRADUATE', 'PGD'), ('Masters', 'MSc')], default='Year one', max_length=30)),
                ('bio', models.CharField(max_length=200)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('matric', models.IntegerField(blank=True, null=True)),
                ('is_teacher', models.BooleanField(default=False, verbose_name='teacher status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
